version: '3.8'

services:
  # =============================================================================
  # BACKEND SERVICE (Flask API)
  # =============================================================================
  backend:
    build: .
    ports:
      - "${BACKEND_PORT:-5055}:${BACKEND_PORT:-5055}"
    environment:
      - PORT=${BACKEND_PORT:-5055}
      - DATABASE_URL=postgresql+psycopg://ai_buddy:ai_buddy_password@db:5432/mental_health
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - ENVIRONMENT=docker
      - DOCKER_ENV=true
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PPLX_API_KEY=${PPLX_API_KEY}
      - AI_PROVIDER=${AI_PROVIDER:-gemini}
      - REDIS_URL=redis://redis:6379
      - VERSION=${VERSION:-1.0.0}
      - BUILD_TIME=${BUILD_TIME:-unknown}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    volumes:
      - ./instance:/app/instance
      - ./flask_session:/app/flask_session
      - .:/app
    networks:
      - ai-buddy-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:${BACKEND_PORT:-5055}/api/health')\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # =============================================================================
  # DATABASE SERVICE (PostgreSQL)
  # =============================================================================
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-mental_health}
      - POSTGRES_USER=${POSTGRES_USER:-ai_buddy}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ai_buddy_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    networks:
      - ai-buddy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ai_buddy}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =============================================================================
  # REDIS SERVICE (Session Storage)
  # =============================================================================
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped
    networks:
      - ai-buddy-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # =============================================================================
  # FLUTTER WEB SERVICE (Frontend)
  # =============================================================================
  flutter-web:
    build:
      context: ./ai_buddy_web
      dockerfile: Dockerfile.web
    ports:
      - "${FLUTTER_WEB_PORT:-8080}:8080"
    environment:
      - API_URL=http://backend:${BACKEND_PORT:-5055}
      - ENVIRONMENT=docker
      - DOCKER_ENV=true
      - VERSION=${VERSION:-1.0.0}
      - BUILD_TIME=${BUILD_TIME:-unknown}
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - ai-buddy-network
    healthcheck:
      test: ["CMD-SHELL", "nginx -t && curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:

networks:
  ai-buddy-network:
    driver: bridge 