version: '3.8'

services:
  web:
    build: .
    ports:
      - "10000:10000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PPLX_API_KEY=${PPLX_API_KEY}
      - AI_PROVIDER=${AI_PROVIDER:-gemini}
      - PORT=10000
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=mental_health
      - POSTGRES_USER=ai_buddy
      - POSTGRES_PASSWORD=ai_buddy_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 