services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/myapp
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=your-secret-key
      - GEMINI_API_KEY=your-gemini-key
      - PPLX_API_KEY=your-pplx-key
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_:
