name: ai_wellness_buddy
description: "AI-powered mental health and academic assistant for students"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  provider: ^6.1.1
  # HTTP Client
  dio: ^5.4.0
  # Local Storage
  shared_preferences: ^2.2.2
  # UI Components
  google_fonts: ^6.1.0
  flutter_markdown: ^0.6.18
  animated_text_kit: ^4.2.2
  # Animations
  lottie: ^2.7.0
  # Utils
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  # Firebase (for future use)
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  # PWA Support
  pwa: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Testing
  mockito: ^5.4.4
  # Build
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#FFFFFF"
    theme_color: "#667eea"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/splash_icon.png
  branding: assets/icons/branding.png
  color_dark: "#1a1a1a"
  image_dark: assets/icons/splash_icon_dark.png
  branding_dark: assets/icons/branding_dark.png

  android_12:
    image: assets/icons/splash_icon.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/icons/splash_icon_dark.png
    icon_background_color_dark: "#1a1a1a" 