services:
  # Backend API Service with Flutter Web
  - type: web
    name: ai-mental-health-backend
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      # Platform flags
      - key: RENDER
        value: true
      - key: ENVIRONMENT
        value: production

      # App config
      - key: AI_PROVIDER
        value: gemini
      - key: CORS_ORIGINS
        value: https://ai-mental-health-backend-3w4b.onrender.com,https://ai-mental-health-assistant-tddc.onrender.com

      # Database: use EXTERNAL connection string to avoid DNS issues
      - key: DATABASE_URL
        fromDatabase:
          name: ai-mvp-db
          property: connectionString

      # Secrets: values are set in Render dashboard (not committed)
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PPLX_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ADMIN_API_TOKEN
        sync: false

      # Retention policy (days)
      - key: MESSAGE_RETENTION_DAYS
        value: "30"
      - key: SESSION_RETENTION_DAYS
        value: "14"
      - key: ERROR_LOG_RETENTION_DAYS
        value: "14"
      - key: ANALYTICS_RETENTION_DAYS
        value: "90"

      # Observability (optional)
      - key: SENTRY_DSN_BACKEND
        sync: false
      - key: SENTRY_TRACES_SAMPLE_RATE
        value: "0"
      - key: SENTRY_PROFILES_SAMPLE_RATE
        value: "0"

      # Informational
      - key: VERSION
        value: 1.0.0
      - key: BUILD_TIME
        generateValue: true
      - key: PLATFORM
        value: render
      - key: PYTHON_VERSION
        value: "3.9.6"