services:
  - type: web
    name: ai-mental-health-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: ./startup.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.6
      - key: DATABASE_URL
        fromDatabase:
          name: ai-mental-health-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PPLX_API_KEY
        sync: false
      - key: AI_PROVIDER
        value: gemini
      - key: PORT
        value: 10000

databases:
  - name: ai-mental-health-db
    databaseName: mental_health
    user: ai_buddy
    plan: free 