name: Mobile Release (Android + iOS)

permissions:
  contents: write

concurrency:
  group: mobile-release-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      # Note: GitHub limits workflow_dispatch inputs to 10. Keep essentials only.
      preflight:
        description: "Run format/analyze/tests before builds?"
        required: false
        default: "false"
      upload_android:
        description: "Upload Android to Google Play after build?"
        required: false
        default: "false"
      upload_ios:
        description: "Upload iOS to TestFlight after build?"
        required: false
        default: "false"
      build_number:
        description: "Unified build number for both platforms (optional). Defaults to run number if empty."
        required: false
        default: ""
      release_notes:
        description: "Unified release notes/changelog (optional)"
        required: false
        default: ""
      app_id:
        description: "Android applicationId override (optional)"
        required: false
        default: "app.mhb.preview"
      package_name:
        description: "Google Play package name (e.g., app.mhb.preview)"
        required: false
        default: "app.mhb.preview"
      android_track:
        description: "Android Play track (internal, alpha, beta, production)"
        required: false
        default: "internal"
      ios_bundle_id:
        description: "iOS bundle identifier"
        required: false
        default: "app.mhb.preview"
      ios_export_method:
        description: "iOS export method (app-store, ad-hoc, development)"
        required: false
        default: "app-store"

jobs:
  android:
    name: Android job
    uses: ./.github/workflows/android_release.yml
    secrets: inherit
    with:
      app_id: ${{ inputs.app_id }}
      package_name: ${{ inputs.package_name }}
      track: ${{ inputs.android_track }}
      build_number: ${{ inputs.build_number }}
      release_notes: ${{ inputs.release_notes }}
      upload: ${{ inputs.upload_android }}
      preflight: ${{ inputs.preflight }}
      environment: beta
      sentry_upload: 'false'
      sentry_org: ''
      sentry_project: ''
      sentry_release: ''
      crashlytics_upload: 'false'

  ios:
    name: iOS job
    uses: ./.github/workflows/ios_release.yml
    secrets: inherit
    with:
      bundle_id: ${{ inputs.ios_bundle_id }}
      scheme: Runner
      export_method: ${{ inputs.ios_export_method }}
      build_number: ${{ inputs.build_number }}
      release_notes: ${{ inputs.release_notes }}
      upload: ${{ inputs.upload_ios }}
      preflight: ${{ inputs.preflight }}
      environment: beta
      sentry_upload: 'false'
      sentry_org: ''
      sentry_project: ''
      sentry_release: ''
      crashlytics_upload: 'false'

  release_notify:
    name: Release and Notify
    runs-on: ubuntu-latest
    needs: [android, ios]
    env:
      DO_GH_RELEASE: ${{ vars.DO_GH_RELEASE || 'false' }}
      DO_SLACK_NOTIFY: ${{ vars.DO_SLACK_NOTIFY || 'false' }}
      TAG_PREFIX: ${{ vars.TAG_PREFIX || 'mobile-v' }}
    steps:
      - name: Download Android artifact
        uses: actions/download-artifact@v4
        with:
          name: android-aab
          path: dist
        continue-on-error: true

      - name: Download iOS IPA artifact
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: dist
        continue-on-error: true

      - name: Compose tag and body
        id: meta
        shell: bash
        env:
          BN: ${{ inputs.build_number }}
          RN: ${{ inputs.release_notes }}
        run: |
          set -e
          BNV="$BN"; [ -z "$BNV" ] && BNV="$GITHUB_RUN_NUMBER"
          TAG="${TAG_PREFIX}${BNV}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "$RN" > RELEASE_BODY.txt
          echo "body_path=$PWD/RELEASE_BODY.txt" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: ${{ env.DO_GH_RELEASE == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.tag }}
          body_path: ${{ steps.meta.outputs.body_path }}
          files: |
            dist/*.aab
            dist/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack notify
        if: ${{ env.DO_SLACK_NOTIFY == 'true' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          set -e
          if [ -z "$SLACK_WEBHOOK_URL" ]; then echo "::warning::SLACK_WEBHOOK_URL not set, skipping"; exit 0; fi
          ANDROID_PRESENT=$(ls dist/*.aab 2>/dev/null | wc -l | xargs)
          IOS_PRESENT=$(ls dist/*.ipa 2>/dev/null | wc -l | xargs)
          MSG="Mobile build completed. Android artifact: $ANDROID_PRESENT, iOS artifact: $IOS_PRESENT. Tag: ${{ steps.meta.outputs.tag }}"
          PAYLOAD=$(printf '{"text":"%s"}' "${MSG//"/\"}")
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"
